theme: jekyll-theme-cayman
title: Alejandro Escalante Mtz
description: algo mas?
show_downloads: true
other:
  docs: https://alejandroescalantemtz.github.io/docs/document_index.html
  test_url: https://www.youtube.com/watch?v=ucAyib45TP8&ab_channel=VictorHugo
  test_in_folder: AlejandroEscalanteMtz.github.io/folder/TESTINGIDK.md
